ru:
  answer:
    negative: "👎 Нет"
    positive: "👍 Да"
    wrong: "Прости, ты должен выбрать да или нет."
  creator: "👨‍💻 Создатель\n\n🇧🇾 @lexvenim"
  error: "💀 Ошибка\n\nИзвини, что-то пошло не так. Лог ошибки был отправлен моему /creator, @lexvenim.\nВо всем вините его. Я не сделала ничего плохого."
  games:
    help: "🕹️ Игры\n\nЧтобы выучить новые слова, лучше всего играть в игры. Я могу предложить две игры: перевод слов или выбор правильного ответа.\nЕсли ты не хочешь играть, введи /cancel или нажми 'Назад'."
    info: "🕹️ Игры\n\nПожалуйста, выбери игру:"
    select:
      help: "🔀 Выбор перевода\n\nПравила просты: я говорю тебе слово и 4 варианта перевода, ты выбираешь правильный. Если ответ верный, мы продолжаем играть. Нет - ты проиграл.\nТы можешь остановить игру, введя /cancel. Или неверный ответ 😀"
      not_enough: "🔀 Выбор перевода\n\nВ твоем словаре недостаточно слов, поэтому мы не можем играть."
      question: "🔀 Выбор перевода\n\n%{stats}Переведи на %{lang}: %{word}"
      result:
        error: "🔀 Выбор перевода\n\nНеверно. Игра окончена.\n\nТвой счет: 💎%{score}."
        success: "Верно!\nТвой счет: 💎%{score}.\n\n"
    repeat:
      help: "🔁 Перевод слов\n\nПравила просты: я говорю тебе слово, ты даешь мне перевод. Если ответ верный, мы продолжаем играть. Нет - ты проиграл.\nТы можешь остановить игру, введя /cancel. Или неверный ответ 😀"
      none: "🔁 Перевод слов\n\nВ твоем словаре нет слов, поэтому мы не можем играть."
      question: "🔁 Перевод слов\n\n${stats}Переведи на %{lang}: %{word}"
      result:
        error: "🔁 Перевод слов\n\nНеверно. Игра окончена.\n\nТвой счет: 💎%{score}."
        success: "Верно!\nТвой счет: 💎%{score}.\n\n"
  hello: "Привет. Меня зовут Ревока. Я могу помочь тебе изучить новый язык. но я не чат-бот!\nВведи /help для информации о командах."
  help:
    creator: "@lexvenim"
    unknown: "Честно говоря, я понятия не имею, что ты делаешь."
  languages:
    flags:
      en: "🇬🇧"
      es: "🇪🇸"
      fr: "🇫🇷"
      ru: "🇷🇺"
    names:
      en: "Английский"
      es: "Испанский"
      fr: "Французский"
      ru: "Русский"
  main:
    help: "Мое имя Ревока. Я могу помочь тебе выучить новый язык.\nЕсли у тебя еще нет словаря, тебе стоит создать новый с помощью команды /new_vocabulary . Новый словарь автоматически станет активным, но если ты хочешь вернуться к другим словарям, набери /switch_vocabulary.\nПустые словари невроятно скучные: добавь слово в словарь с помощью команды /add_word.\nЕсли ты не знаешь перевода, лучше всего набрать команду /translate_word и затем добавить слово в словарь.\nДля того, чтобы потренироваться, набери /random_word или /random_translation , чтобы получить случайное слово из словаря для перевода.\nСписок всех слов словаря доступен по команде /list_words.\nЧтобы удалить словарь, используй команду /delete_vocabulary.\nДля изменения частоты оповещений воспользуйся командой /change_notification_settings и следуй инструкциям.\nТы так же можешь поменять мойосновной язык командой /change_language.\nНадеюсь, тебе понравится работать со мной. Но давай не будем болтать по мелочам."
    info: "Назад к меню..."
  menu:
    back: "⬅️ Назад"
    daytime:
      day: "☀️ День"
      evening: "🌆 Вечер"
      morning: "🌅 Утро"
      night: "🌙 Ночь"
    games:
      select: "🔀 Выбор перевода"
      translate: "🔁 Перевод слов"
    help: "❓ Помощь"
    hour:
      one: "🕐"
      two: "🕑"
      three: "🕒"
      four: "🕓"
      five: "🕔"
      six: "🕕"
      seven: "🕖"
      eight: "🕗"
      nine: "🕘"
      ten: "🕙"
      eleven: "🕚"
      twelve: "🕛"
    main:
      games: "🕹️ Игры"
      settings: "🔧 Настройки"
      translate: "💻 Переводчик"
      vocabulary: "📖 Словари"
      word: "📋 Слова"
    notify:
      day: "1 день"
      day_two: "2 дня"
      hour_one: "1 час"
      hour_two: "2 часа"
      hour_four: "4 часа"
      hour_six: "6 часов"
      hour_twelve: "12 часов"
      never: "Никогда"
      week: "1 неделя"
    settings:
      info: "ℹ️ Информация"
      language: "📜 Язык"
      notifications: "⏰ Частота оповещений"
      sleep: "🛏️ Часы сна"
    vocabularies:
      add: "📕 Добавить словарь"
      list: "📃 Список словарей"
      switch: "📚 Поменять словарь"
      delete: "🗑️ Удалить словарь"
    words:
      add: "✏️ Добавить слово"
      list: "📝 Список слов"
  settings:
    help: "🔧 Настройки\n\nЗдесь ты можешь просмотреть и поменять настройки оповещений. Выбери 'Периодичность' если хочешь изменить, как часто будешь получать мои оповещения. Выбери 'Часы сна', если хочешь изменить время, когда я не должна тебя беспокоить.\nЕсли ты не хочешь менять настройки, введи /cancel или нажми 'Назад'."
    info: "🔧 Настройки\n\nВыбери, что ты хочешь поменять:"
    language:
      choice: "📜 Язык\n\nВыбери язык, на котором хочешь вести общение со мной:"
      help: "📜 Язык\n\nЗдесь ты можешь изменить язык общения со мной. Сейчас я разговариваю с тобой на Русском, но ты так же можешь переключиться на другие языки.\nЕсли ты не хочешь менять язык общения, введи /cancel или нажми 'Назад'."
      result:
        error: "Что-то пошло не так. Язык общения останется тем же."
        success: "Язык общения изменен."
    notify:
      help: "⏰ Частота оповещений\n\nЗдесь ты можешь поменять, как часто ты хочешь получать мои оповещения. 1 час является минимумом, 1 неделя - максимумом.\nНо если ты выставил часы сна, то оповещения будут приходить после них.\nЕсли ты не хочешь менять частоту оповещений, введи /cancel или нажми 'Назад'."
      info: "⏰ Частота оповещений\n\nКак часто ты хочешь получать мои оповещения?"
      no_vocabulary: "Извини, у тебя все еще нет словарей. Создай словарь и тогда сможешь пользоваться оповещениями."
      none: "⏰ Частота оповещений\n\nОповещения отключены."
      result:
        error: "Что-то пошло не так. Настройки оповещений не изменятся."
        success: "Настройки оповещений изменены."
    sleep:
      end: 
        daytime: "🛏️ Часы сна\n\nВыбери, когда заканчиваются часы сна:"
        hour: "🛏️ Часы сна\n\nВыбери час, когда заканчиваются часы сна:"
        wrong: "Неверный ввод. Попробуй еще раз."
      help: "🛏️ Часы сна\n\nЗдесь ты можешь изменять часы сна.Сначала тебе предложат выбрать часть дня, когда начинаются часы сна, затем точное время их начала. Затем то же самое потребуется сделать и со временем их окончания.\nЕсли ты не хочешь менять часы сна, введи /cancel или нажми 'Назад'."
      result:
        error: "Что-то пошло не так. Часы сна не были изменены"
        success: "Часы сна были изменены."
      start: 
        daytime: "🛏️ Часы сна\n\nВыбери, когда начинаются часы сна:"
        hour: "🛏️ Часы сна\n\nВыбери час, когда начинаются часы сна:"
        wrong: "Неверный ввод. Попробуй еще раз."
    summary: 
      intro: "🔧 Настройки\n\n"
      language: "Язык общения %{lang}."
      notify:
        negative: "Оповещения отключены.\n\n" 
        positive: "Оповещения приходят %{tick}.\n\n"
      sleep: "Мои часы сна начинаются в %{hour_start}:00 и заканчиваются в %{hour_end}:00.\n\n"
  time:
    day: "день"
    days: "дня"
    every:
      day: "каждый %{period} день"
      days: "каждые %{period} дня"
      hour: "каждый %{period} час"
      hours_1: "каждые %{period} часа"
      hours_2: "каждые %{period} часов"
      week: "каждую %{period} неделю"
    hour: "час"
    hours_1: "часа"
    hours_2: "часов"
    week: "неделю"
  translate:
    help: "💻 Переводчик\n\nОн переведет любое введенное тобой слово. Наверное. Попробуй в любом случае!"
    save:
      none: "У тебя нет слов, которые можно сохранить."
      result:
        error: "Что-то пошло не так. Слово не было добавлено."
        success: "%{word} было добавлено в словарь."
    translation: "💻 Переводчик\n\nПеревод: %{translation}.\nЕсли ты хочешь сохранить слово в словарь, введи /save."
    word: "💻 Переводчик\n\nВведи слово для перевода:"
  vocabularies:
    delete:
      help: "🗑️ Удалить словарь\n\nЗдесь ты можешь удалить любой словарь (если у тебя их хотя бы два).\nЕсли ты не хочешь удалять словаи, введи /cancel или нажми 'Назад'."
      list: "🗑️ Удалить словарь\n\nВыбери словарь, который хочешь удалить:"
      none: "🗑️ Удалить словарь\n\nУ тебя нет словарей. Нечего удалять."
      one: "🗑️ Удалить словарь\n\nУ тебя только один словарь. Нельзя удалить последний словарь."
      result:
        error: "Что-то пошло не так. Словарь не был удален."
        success: "Словарь был удален."
    help: "📖 Словари\n\nЗдесь ты можешь управлять своими словарями. Ты можешь создавать словари, переключаться между ними и удалять.\nЕсли ты не хочешь ничего делать со словарями, введи /cancel или нажми 'Назад'."
    info: "📖 Словари\n\nВыбери, что ты хочешь сделать:"
    list: 
      main: "У тебя %{num} словарей:\n%{vocs}"
      voc: "%{name}: %{count} слов"
    new:
      exist: "📕 Добавить словарь\n\nУ тебя уже есть такой словарь. Зачем тебе еще один?"
      help: "📕 Добавить словарь\n\nЗдесь ты можешь создать новый словарь. Сначала выбери язык, который хочешь изучить, затем язык, который уже знаешь.\nЕсли ты не хочешь создавать словарь, введи /cancel или нажми 'Назад'."
      identical: "📕 Добавить словарь\n\nТы выбрал одинаковые языки. Не думаю, что ты так выучишь что-нибудь."
      know: "📕 Добавить словарь\n\nВыбери язык, который уже знаешь:"
      learn: "📕 Добавить словарь\n\nВыбери язык, который хочешь изучить:"
      result:
        error: "Что-то пошло не так. Словарь не был создан."
        success: "Словарь был создан."
      wrong: "📕 Добавить словарь\n\nПожалуйста введи или выбери словарь правильно." 
    switch:
      help: "📚 Поменять словарь\n\nЗдесь ты можешь переключаться между словарями (если у тебя их хотя бы два).\nЕсли ты не хочешь менять свой текущий словарь, введи /cancel или нажми 'Назад'."
      list: "📚 Поменять словарь\n\nВыбери словарь, на который хочешь переключиться:"
      none: "📚 Поменять словарь\n\nУ тебя нет словарей. Нельзя переключиться."
      one: "📚 Поменять словарь\n\nУ тебя всего лишь один словарь."
      result:
        error: "Что-то пошло не так. Текущий словарь не изменился."
        success: "Словарь был изменен."
  words:
    help: "📋 Слова\n\nЗдесь ты можешь управлять словами в словаре. Ты можешь добавлять новые слова и просматривать слова в словаре.\nЕсли не хочешь добавлять слова, введи /cancel или нажми 'Назад'."
    info: "📋 Слова\n\nВыбери, что ты хочешь сделать:"
    list: "%{num} слов в твоем %{llang}-%{klang} словаре:\n%{words}"
    new:
      more: "Хочешь добавить еще переводы?"
      result:
        error: "Что-то пошло не так. Слово не было добавлено."
        success: "%{word} было добавлено в словарь."
      translation: "✏️ Добавить слово\n\nВозможный перевод: %{possible_translation}.\n\nВведи перевод:"
      word: "✏️ Добавить слово\n\nВведи слово:"
  todo: "Извини, эта функция пока не добавлена."
  unknown: "Это не является командой. Я не понимаю тебя. Я могу помочь выучить новые слова, но я не чат-бот!"